-- Create Users table
CREATE TABLE IF NOT EXISTS Users (
  UserID SERIAL PRIMARY KEY,
  Username VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  FullName VARCHAR(255) NOT NULL,
  Membership VARCHAR(20) NOT NULL CHECK (Membership IN ('Premium', 'Normal')),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Post table
CREATE TABLE IF NOT EXISTS Post (
  PostID SERIAL PRIMARY KEY,
  Title VARCHAR(255) NOT NULL,
  Body TEXT NOT NULL,
  CategoryID INT NOT NULL,
  Status VARCHAR(20) NOT NULL CHECK (Status IN ('Draft', 'Published', 'Pending Review')),
  Label VARCHAR(20) NOT NULL CHECK (Label IN ('Normal', 'Premium')),
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Category table
CREATE TABLE IF NOT EXISTS Category (
  CategoryID SERIAL PRIMARY KEY,
  Name VARCHAR(255) NOT NULL,
  Description TEXT,
  Activated BOOLEAN NOT NULL DEFAULT true,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Payment table
CREATE TABLE IF NOT EXISTS Payment (
  PaymentID SERIAL PRIMARY KEY,
  Amount DECIMAL(10, 2) NOT NULL,
  PaymentMethod VARCHAR(255) NOT NULL,
  Status VARCHAR(20) NOT NULL,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
